//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLO128.Calculator.Domain.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KLO128.Calculator.Domain.Shared.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Operators.
        /// </summary>
        public static string AdvancedOperators {
            get {
                return ResourceManager.GetString("AdvancedOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Version.
        /// </summary>
        public static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculator.
        /// </summary>
        public static string Calculator {
            get {
                return ResourceManager.GetString("Calculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute.
        /// </summary>
        public static string Compute {
            get {
                return ResourceManager.GetString("Compute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string decimalPoint {
            get {
                return ResourceManager.GetString("decimalPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the culture specified: {0}.
        /// </summary>
        public static string exp001 {
            get {
                return ResourceManager.GetString("exp001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cannot start with operator &apos;{0}&apos;..
        /// </summary>
        public static string exp002 {
            get {
                return ResourceManager.GetString("exp002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many operands..
        /// </summary>
        public static string exp003 {
            get {
                return ResourceManager.GetString("exp003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number is in invalid format: {0} ...at index: {1}.
        /// </summary>
        public static string exp004 {
            get {
                return ResourceManager.GetString("exp004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported operation: &apos;{0}&apos; ...at index: {1}.
        /// </summary>
        public static string exp005 {
            get {
                return ResourceManager.GetString("exp005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid expression: Too many operands in binary expression. Expected an operator near the operand: {0}... at index: {1}..
        /// </summary>
        public static string exp006 {
            get {
                return ResourceManager.GetString("exp006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token occurred &apos;{0}&apos; at index: {1}.
        /// </summary>
        public static string exp007 {
            get {
                return ResourceManager.GetString("exp007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing operand in binary expression... at index: {0}.
        /// </summary>
        public static string exp008 {
            get {
                return ResourceManager.GetString("exp008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing closing bracket... Context starts at index: {0}.
        /// </summary>
        public static string exp009 {
            get {
                return ResourceManager.GetString("exp009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many operators at index {0}. Unexpected operator: {1}.
        /// </summary>
        public static string exp010 {
            get {
                return ResourceManager.GetString("exp010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing oppenning bracket... Context ends at index: {0}.
        /// </summary>
        public static string exp011 {
            get {
                return ResourceManager.GetString("exp011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is able to compute any constant complex binary expression using supported operators and brackets. It can also pretify or normalize the expression and the result as well as it displays a history from cookies..
        /// </summary>
        public static string msgAbout {
            get {
                return ResourceManager.GetString("msgAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression field is required..
        /// </summary>
        public static string msgExpressionRequired {
            get {
                return ResourceManager.GetString("msgExpressionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Result as Integer.
        /// </summary>
        public static string msgResultAsInteger {
            get {
                return ResourceManager.GetString("msgResultAsInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is not responding....
        /// </summary>
        public static string msgServerNotResponding {
            get {
                return ResourceManager.GetString("msgServerNotResponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch protocol to https for preservation of history....
        /// </summary>
        public static string msgSwitchToHttps {
            get {
                return ResourceManager.GetString("msgSwitchToHttps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No History.
        /// </summary>
        public static string NoHistory {
            get {
                return ResourceManager.GetString("NoHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prettify.
        /// </summary>
        public static string Prettify {
            get {
                return ResourceManager.GetString("Prettify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Thousand Separators.
        /// </summary>
        public static string UseThousandSeparators {
            get {
                return ResourceManager.GetString("UseThousandSeparators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Api Version.
        /// </summary>
        public static string WebApiVersion {
            get {
                return ResourceManager.GetString("WebApiVersion", resourceCulture);
            }
        }
    }
}
